name: Build pull request

on:
  pull_request:
    branches: 
      - '*'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: 'dotnet restore'
        run: dotnet restore
      - name: 'dotnet build'
        run: dotnet build --configuration Release
      - name: 'dotnet test'
        run: dotnet test 
