name: Release

on:
  release:
     types: [published, deleted]
     
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Application released
      
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: abatilo
          repo: release-info-action
          
      - name: Example of consumption of the output
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
          echo "Version $LATEST was released at $LATEST_DATE"
